### ISSUE TITLE
image icon size wrong 

### ISSUE THREAD

**Issue by NobodyForNothing** [NobodyForNothing/blood-pressure-monitor-fl#240]
- white background on some launchers
- clipped

![image](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/82763757/5dc2836d-dc83-4155-8308-5eab9a6cbb07)

**Comment by sebastien46** [comment]
Can you try with this icon @NobodyForNothing ?
I added the proper amount of padding.

![icon](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/57289288/28cb27ec-0815-47f0-820c-b5070e6cba5d)

**Comment by sebastien46** [comment]
> * white background on some launchers

The reason why it's now white is because I set the background color to `android:white`, because I didn't know which color to put here since your original icon didn't have one.

I tried implementing it without specifying `<background/>`

> * clipped

I used the padded icon above, it works now.
I also removed the `background` field entirely from `ic_launcher`, now it defaults to black when put on the launcher & transparent when moved around.

Note: the background of adaptive icons cannot be transparent, it must be set to a specific drawable / color value.

![scr3_adapt_bg](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/57289288/abc854cf-3947-49f3-bf52-1ee588721a54)

**Comment by NobodyForNothing** [comment]
@sebastien46 Thanks for the resized icon, it is helpful in case your other vector icon doesn't get included until the next release.

It makes sense that the adaptive icon doesn't have a transparent background. I track this in a separate issue because this was an issue before your PR and further investigation is needed.
