### ISSUE TITLE
Translation questions

### ISSUE THREAD

**Issue by pimlie** [NobodyForNothing/blood-pressure-monitor-fl#408]
Hey, just found this awesome app. Thanks for this!

As Dutch was missing I just finished adding Dutch translations on weblate, but there were a couple of strings that weren't clear to me what they meant:

- Pulse could refer to heart rate and the difference between sys/dia pressures. To be sure, can you confirm that only the string `pulsePressure` is used for the sys/dia pressure context and that all other pulse strings like `pulLong`, `irregularPulseDetected` etc refer to heart rate?
- I'm not sure what `Time-Resolved Metrics` are? Does this refer to statistical averages over time?
- The string `warnNeedsRestartForUsingApp` has an english translation of _Files where deleted this session. Restart the app to continue using returning to other parts of the app!_. Unfortunately I'm not sure I fully understand what is meant with this, when/why is this string used?

Btw, when a build with Dutch is available I might need to take a second pass at some strings to make them better fit.

**Comment by NobodyForNothing** [comment]
Thanks allot for your interest in translating this app!

- Yes, pulsePressure is the only one computed from sys/dia, the other pulse values mean heart rate.
- Time resolved metrics mean the average sys/dia/pul value in relation to the time of day. So when for example the sys value has an average of 130 at 8 am but and average of 110 during the rest of the day, you would see a peak at 8 am in the clock shaped (round) chart. I'm aware that the caption is quite vague, please feel free to suggest something more fitting.
- Seems like I messed `warnNeedsRestartForUsingApp` up somehow. It was intended to tell the user that the app needs to be restarted. Don't worry about it since it will be deleted with the next release.

I plan to make a release within the next few days anyways, so you don't have to wait allot to see your strings. Don't worry about submitting changes, translation is an always ongoing effort :).

**Comment by NobodyForNothing** [comment]
I think this is no longer needed.
