### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by thatso** [NobodyForNothing/blood-pressure-monitor-fl#66]
**What happened**
I've exported my data from version 1.3.0 as CSV. The file is perfectly fine and readable with my PC. However, import in version 1.3.2 fails with "This file can't be imported".

**ideas**
I've double-checked the field and text delimiters, they match the CSV file.
After reinstallation of the app, import now just states "Successfully imported 0 entries". :confused:
Import in version 1.3.1 succeeds, but afterwards the statistics page stays empty.

**Comment by NobodyForNothing** [comment]
Thanks for the report. This issue occurs due to a change of the line ending in a csv export to better confirm the csv standard RFC 4180. A quick fix would be to add a carriage return before every new line.
I can confirm the bug and will add backwards compatibility in the next update.

> Import in version 1.3.1 succeeds, but afterwards the statistics page stays empty.

The empty statistics page was a issue with that particular version.
